ALTER TABLE products
    ADD COLUMN IF NOT EXISTS country_of_production VARCHAR(255) NOT NULL DEFAULT 'N/A',
    ADD COLUMN IF NOT EXISTS volume DECIMAL(10, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sex VARCHAR(255) NOT NULL DEFAULT 'Unisex';