basePath: /v2
definitions:
  ga_marketplace_internal_http_datatransfers_requests.UserSendOTPRequest:
    properties:
      phone:
        type: string
    required:
    - phone
    type: object
  internal_http_handlers.BaseResponse:
    properties:
      message:
        type: string
      payload: {}
      status:
        type: integer
    type: object
host: product_info.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server with null types overridden with primitive types.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GA Marketplace API
  version: "1.0"
paths:
  /auth/send-otp:
    post:
      consumes:
      - application/json
      description: Send OTP to user's phone number
      parameters:
      - description: send otp request
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/ga_marketplace_internal_http_datatransfers_requests.UserSendOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_http_handlers.BaseResponse'
      summary: Send OTP
      tags:
      - users
swagger: "2.0"
